### PR TITLE
Constrain memory consumption by using batched promise execution

### LINKED ISSUE #74: Memory issues when trying to export large datasets
We use `node-firestore-import-export` on a daily basis for im/export of several test Firestore instances. Next to that we use it as a secondary backup path for production. Or production database is growing quite large, and we run into memory issues when resolving 20.000+ promises simultaneously.

### Expected behavior
A successful export via Cloud Function

### Actual behavior

```
Error: memory limit exceeded. Function invocation was interrupted.
Error: function crashed out of request scope Function invocation was interrupted.
```

### Steps to reproduce the behavior
Create a DB with several collections with far over 20.000 documents, and try to run an export via a Cloud Function.

### PR DESCRIPTION
**Pull request by Endran**
Fixes #74 .

Instead of `await Promise.all`, use a batched approach. All promises could mean 20.000+ promises, which is to much for the max RAM that a Cloud Function can handle. Using this batched approach the memory consumption is constrained, but it is still as performant timewise as without batching. 
The order of the documents might change due to timing issues, but the overall content is identical.

### CODE REVIEW

File: src/lib/firestore-helpers.ts [hunk 1]
```diff
@@ -46,11 +46,25 @@ const isRootOfDatabase = (ref: admin.firestore.Firestore |
 
 const sleep = (timeInMS: number): Promise<void> => new Promise(resolve => setTimeout(resolve, timeInMS));
 
+const batchExecutor = async function<T>(promises: Promise<T>[], batchSize: number = 50) {
+  const res: T[] = [];
+  while (promises.length > batchSize) {
```
Comment (jloosli) [inline src/lib/firestore-helpers.ts]:
```suggestion
  while (promises.length > 0) {
```

File: src/lib/firestore-helpers.ts [hunk 2]
```diff
@@ -46,11 +46,25 @@ const isRootOfDatabase = (ref: admin.firestore.Firestore |
...
+    const temp = await Promise.all(promises.splice(0, batchSize));
+    res.push(...temp)
+  }
+  if (promises.length > 0) {
```
Comment (jloosli) [inline src/lib/firestore-helpers.ts]:
```suggestion
```

File: src/lib/firestore-helpers.ts [hunk 3]
```diff
@@ -46,11 +46,25 @@ const isRootOfDatabase = (ref: admin.firestore.Firestore |
...
+    const temp = await Promise.all(promises);
```
Comment (jloosli) [inline src/lib/firestore-helpers.ts]:
```suggestion
```

File: src/lib/firestore-helpers.ts [hunk 4]
```diff
@@ -46,11 +46,25 @@ const isRootOfDatabase = (ref: admin.firestore.Firestore |
...
+    res.push(...temp)
```
Comment (jloosli) [inline src/lib/firestore-helpers.ts]:
```suggestion
```

File: src/lib/firestore-helpers.ts [hunk 5]
```diff
@@ -46,11 +46,25 @@ const isRootOfDatabase = (ref: admin.firestore.Firestore |
...
+  }
```
Comment (jloosli) [inline src/lib/firestore-helpers.ts]:
```suggestion
```

**Comment by jay8t6** [comment]
@Endran this PR still doesn't solve the following issue when large datasets are exported:

Error: function crashed out of request scope Function invocation was interrupted.

However, strangely it works once every few attempts. It fails most of the time. Could you help?

**Comment by Endran** [comment]
Hi, yeah.. we started running into the issue once more. It appears that the actual creating of all the promises of all the data is the one that goes out of memory. So we shouldn't just execute the promises batch wise (although it helps), but we should also make the promises batch wise. I guess firebase will already hoards resources for each document.

This is quite the rewrite, since at the moment all collections are handled simultaneously as well. We decided to write our own small exporter, which goes by each collection one by one, and creates document promises in batches. We also stream everything to file, instead of keeping them in mem. This alters the exported file structure, but we reused the document format (serializeSpecialTypes). 
Now we are able to export massive files. See https://www.npmjs.com/package/@endran/firestore-export-import .
